---
- name: Install Python
  ansible.builtin.import_tasks: python.yml
  when: install.python

- name: Install Npm
  ansible.builtin.import_tasks: npm.yml
  when: install.npm

- name: Install Java 21
  ansible.builtin.import_tasks: java.yml
  when: install.java

- name: Install Go
  ansible.builtin.import_tasks: go.yml
  when: install.go
