- name: Install Python and pip
  become: true
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip
    - python3-venv
    state: present
    update_cache: true
  tags:
  - programming_languages
  - python
