- name: Add Docker GPG key
  become: true
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    executable: /bin/bash
  tags:
    - docker

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  tags:
    - docker

- name: Install Docker and Docker Compose
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
  tags: 
    - docker

- name: Ensure Docker service is running
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: Add user to docker group (avoiding sudo for Docker commands)
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  when: ansible_user_id != 'root'
  tags: 
    - docker

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false
  tags:
    - docker

- name: Display installed Docker version
  ansible.builtin.debug:
    msg: "Docker version: {{ docker_version.stdout }}"
  tags:
    - docker