---
- name: Ensure Neovim directory exists in /opt
  ansible.builtin.file:
    path: /opt/nvim
    state: directory
    mode: "0755"
  become: true
  tags:
    - neovim

- name: Download Neovim AppImage
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
    dest: "/opt/nvim/nvim"
    mode: "0755"
  become: true
  tags:
    - neovim

- name: Create a symbolic link to /usr/local/bin
  ansible.builtin.file:
    src: "/opt/nvim/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
  become: true
  tags:
    - neovim

- name: Ensure Neovim is in the PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$PATH:/opt/nvim/"'
    create: true
    insertafter: EOF
    state: present
  tags:
    - neovim

- name: Reload shell to apply changes
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
  tags:
    - neovim

- name: Verify Neovim installation
  ansible.builtin.command: /usr/local/bin/nvim --version
  register: neovim_version
  changed_when: false
  tags:
    - neovim

- name: Output Neovim version
  ansible.builtin.debug:
    msg: "Neovim installed successfully: {{ neovim_version.stdout }}"
  tags:
    - neovim

- name: Ensure ~/.config/nvim exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: "0755"
  tags:
    - neovim

- name: Check if Kickstart is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
  register: kickstart_installed
  tags:
    - neovim

- name: Download and Install Kickstart
  ansible.builtin.git:
    repo: "https://github.com/nvim-lua/kickstart.nvim.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: true
    force: true
  when: not kickstart_installed.stat.exists
  tags:
    - neovim

- name: Launch Terminal and Start Neovim
  ansible.builtin.command: gnome-terminal -- bash -c "nvim; exec bash"
  async: 10
  poll: 0
  changed_when: false
  when: not kickstart_installed.stat.exists
  tags:
    - neovim
