---
- name: Check if Obsidian is installed
  ansible.builtin.shell: "flatpak list --app | grep -q md.obsidian.Obsidian"
  register: obsidian_installed
  changed_when: false
  ignore_errors: true
  tags:
    - obsidian

- name: Install Obsidian
  ansible.builtin.command: flatpak install --user --noninteractive md.obsidian.Obsidian
  when: install.obsidian and obsidian_installed.rc != 0
  tags:
    - obsidian
