---
- name: Check if VSCode is installed
  ansible.builtin.shell: "flatpak list --app | grep com.visualstudio.code"
  register: vscode_installed
  changed_when: false
  failed_when: vscode_installed.rc > 1
  tags:
    - vscode

- name: Install VSCode
  ansible.builtin.command: flatpak install --user -y flathub com.visualstudio.code
  when: (install.vscode | default(true)) and vscode_installed.rc != 0
  tags:
    - vscode

- name: Verify VS Code installation
  ansible.builtin.command: flatpak run com.visualstudio.code --version
  register: vscode_check
  changed_when: false
  tags:
    - vscode

- name: Ensure VS Code is recognized
  ansible.builtin.debug:
    msg: "VS Code installed at {{ vscode_check.stdout }}"
  tags:
    - vscode

- name: Create VSCode wrapper script for `code .`
  ansible.builtin.copy:
    dest: "/usr/local/bin/code"
    mode: '0755'
    content: |
      #!/bin/bash
      flatpak run com.visualstudio.code "$@"
  become: true
  tags:
    - vscode

- name: Ensure VSCode has access to home directory
  ansible.builtin.command: flatpak override --user com.visualstudio.code --filesystem=$HOME
  changed_when: false
  tags:
    - vscode

- name: Install VS Code extensions
  ansible.builtin.command: flatpak run com.visualstudio.code --install-extension {{ item }} --force
  loop: "{{ vscode_extensions.values() | list | flatten }}"
  register: vscode_extension_install
  changed_when: "'already installed' not in vscode_extension_install.stdout"
  tags:
    - vscode

- name: Show installed extensions
  ansible.builtin.command: flatpak run com.visualstudio.code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
  tags:
    - vscode

- name: Display installed extensions
  ansible.builtin.debug:
    msg: "Installed extensions: {{ vscode_installed_extensions.stdout_lines }}"
  tags:
    - vscode
