---
- name: Ensure .bash_aliases exists
  ansible.builtin.file:
    path: ~/.bash_aliases
    state: touch
    mode: "0644"
  tags:
    - aliases

- name: Comment out predefined aliases in .bashrc
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "^(alias (ls|dir|vdir|ll|la|l)=.*)$"
    replace: "# \\1"
  tags:
    - aliases

- name: Set up Bash aliases
  ansible.builtin.lineinfile:
    path: ~/.bash_aliases
    line: 'alias {{ item.key }}="{{ item.value }}"'
    create: true
    state: present
    regexp: "^alias {{ item.key }}="
  loop: "{{ bash_aliases.general | dict2items + bash_aliases.git | dict2items + bash_aliases.docker | dict2items }}"
  register: alias_setup
  tags:
    - aliases

- name: Ensure .bash_aliases is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases"
    create: true
    insertafter: EOF
    state: present
  mode: "0644"
  register: bashrc_update
  tags:
    - aliases

- name: Reload shell to apply changes
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
  when: alias_setup.changed or bashrc_update.changed
  tags:
    - aliases
