- name: Configure Git settings
  become: false
  ansible.builtin.command: >
    git config --global {{ item.key }} "{{ item.value }}"
  loop:
  - { key: user.name, value: "{{ git_config.user_name }}" }
  - { key: user.email, value: "{{ git_config.user_email }}" }
  - { key: core.editor, value: "{{ git_config.editor }}" }
  tags:
  - aliases
  - git

- name: Ensure .bash_aliases exists
  ansible.builtin.file:
    path: ~/.bash_aliases
    state: touch
    mode: '0644'
  tags:
  - aliases

- name: Set up Bash aliases
  ansible.builtin.lineinfile:
    path: ~/.bash_aliases
    line: 'alias {{ item.key }}="{{ item.value }}"'
    create: true
    state: present
    regexp: '^alias {{ item.key }}='
  loop: "{{ bash_aliases.general | dict2items + bash_aliases.git | dict2items + bash_aliases.docker | dict2items }}"
  tags:
  - aliases

- name: Ensure .bash_aliases is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases"
    create: true
    insertafter: EOF
    state: present
  tags:
  - aliases

- name: Reload shell to apply changes
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
  when: bash_aliases is changed
  tags:
  - aliases
